Changed to use tomcat-base (CADC-13798)
opencadc/cadc-target-resolver pull request #27
Opened 2024-11-01 23:00 UTC by andamian

2024-11-04 18:16 UTC, at88mph requested changes

2024-11-04 18:16 UTC, at88mph commented on src/main/webapp/service.yaml
> +          values:
The `values` property is not allowed.  This should be `enum`.

2024-11-04 18:16 UTC, at88mph commented on src/main/webapp/service.yaml
> +          values:
The `values` property is not allowed.  This should be `enum`.

2024-11-04 18:16 UTC, at88mph commented on src/main/webapp/service.yaml
> +          values:
The `values` property is not allowed.  This should be `enum`.

2024-11-04 18:16 UTC, at88mph commented on src/main/webapp/service.yaml
> +          values:
The `values` property is not allowed.  This should be `enum`.

2024-11-05 17:01 UTC, at88mph commented on VERSION
> +TAGS="${VER} ${VER}-$(date --utc +"%Y%m%dT%H%M%S")"
Can you please make this one last change as well?

2024-11-05 17:41 UTC, at88mph approved these changes

2024-11-05 17:42 UTC, merged

2024-11-05 17:42 UTC, andamian commented on VERSION
> +TAGS="${VER} ${VER}-$(date --utc +"%Y%m%dT%H%M%S")"
Done - thanks